name: Publish to GitHub Packages

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    uses: cboone/gh-actions/.github/workflows/npm-publish.yml@main
    with:
      node-version: "20"
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
